  
name: Update Apache Airflow Containers

on:
  push:
    branches: [develop]
    paths:
      - .github/workflows/apache-airflow-2.yml
  workflow_dispatch:
jobs:
  DockerImage:
    name: apache/airflow:master-python3.8
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CWBICI_DEVELOP_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CWBICI_DEVELOP_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.CWBICI_DEVELOP_AWS_DEFAULT_REGION }}
      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull Image; Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: apache/airflow
          IMAGE_TAG: master-python3.8
        run: |
          docker pull apache/airflow:master-python3.8
          docker tag apache/airflow:master-python3.8 $ECR_REGISTRY/$ECR_REPOSITORY:master-python3.8
          docker tag apache/airflow:master-python3.8 $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:master-python3.8
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: ECR Logout
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
