  
name: Update Pgadmin4 Containers

on:
  push:
    branches: [develop]
    paths:
      - .github/workflows/pgadmin4.yml
  workflow_dispatch:
jobs:
  DockerImage:
    name: pgadmin4
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.RSGISCI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.RSGISCI_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.RSGISCI_AWS_DEFAULT_REGION }}
      - name: ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull Image; Push to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pgadmin4
        run: |
          docker pull dpage/pgadmin4:latest
          docker tag dpage/pgadmin4:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: ECR Logout
        if: always()
        run: docker logout ${{ steps.login-ecr.outputs.registry }}
